name: sway
base: core20
adopt-info: sway
summary: i3-compatible Wayland compositor
description: |
  sway is an i3-compatible Wayland compositor.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  build-deps:
    plugin: nil
    build-packages:
    - ninja-build
    - pkg-config

  wayland:
    source: https://gitlab.freedesktop.org/wayland/wayland.git
    source-tag: "1.20.0"
    source-depth: 1
    plugin: meson
    build-packages:
    - libffi-dev
    - libexpat1-dev
    meson-parameters:
    - -Dtests=false
    - -Ddocumentation=false
    - -Ddtd_validation=false

  wayland-protocols:
    source: https://gitlab.freedesktop.org/wayland/wayland-protocols.git
    source-tag: "1.24"
    source-depth: 1
    plugin: meson
    meson-parameters:
    - -Dtests=false

  drm:
    source: https://gitlab.freedesktop.org/mesa/drm.git
    source-tag: "libdrm-2.4.109"
    source-depth: 1
    plugin: meson
    build-packages:
    - libpciaccess-dev
    stage-packages:
    - libpciaccess0

  seat:
    source-type: git
    source: https://git.sr.ht/~kennylevinsen/seatd
    source-tag: "0.6.3"
    source-depth: 1
    plugin: meson

  wlroots:
    after: [wayland, wayland-protocols, drm, seat]
    source: https://gitlab.freedesktop.org/wlroots/wlroots.git
    # source-tag: "0.15.0"
    source-depth: 1
    plugin: meson
    meson-parameters:
    - -Dxwayland=disabled
    # - -Dexamples=false
    override-build: |
      snapcraftctl build
      cp ${SNAPCRAFT_PART_BUILD}/tinywl/tinywl ${SNAPCRAFT_STAGE}/usr/local/bin/
    # override-stage: |
    #   snapcraftctl stage
    #   cp ${SNAPCRAFT_PART_BUILD}/tinywl/tinywl ${SNAPCRAFT_STAGE}/bin/
    build-packages:
    - libdrm-dev
    - libgbm-dev
    - libxkbcommon-dev
    - libudev-dev
    - libpixman-1-dev
    stage-packages:
    - libegl1
    - libevdev2
    - libgbm1
    - libgles2
    - libglvnd0
    - libgudev-1.0-0
    - libinput10
    - libmtdev1
    - libpixman-1-0
    - libwacom2
    - libxkbcommon0

  sway:
    after: [wlroots]
    source: https://github.com/swaywm/sway.git
    # source-tag: "1.6.1"
    # source-depth: 1
    plugin: meson
    # set snap version via git tag
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version `git tag -l --sort=-creatordate | head -n 1`
    build-packages:
    - libjson-c-dev
    - libpcre3-dev
    - libcairo2-dev
    - libpango1.0-dev
    - libgles-dev
    - libevdev-dev
    - libinput-dev
    stage-packages:
    - libcairo2
    - libdatrie1
    - libfontconfig1
    - libfreetype6
    - libfribidi0
    - libgraphite2-3
    - libharfbuzz0b
    - libpango-1.0-0
    - libpangocairo-1.0-0
    - libpangoft2-1.0-0
    - libpng16-16
    - libthai0
    - libx11-6
    - libxcb-render0
    - libxcb-shm0
    - libxext6
    - libxrender1

  launcher:
    after: [sway]
    plugin: nil
    override-prime: |
      cp ${SNAPCRAFT_STAGE}/usr/local/bin/tinywl ${SNAPCRAFT_PRIME}/usr/local/bin/tinywl
      echo -e "#!/usr/bin/bash\nseatd-launch -- sway" > sway-launch
      chmod +x sway-launch
      echo -e "#!/usr/bin/bash\nseatd-launch -- tinywl" > tinywl-launch
      chmod +x tinywl-launch

apps:
  sway:
    # command: usr/local/bin/sway
    command: sway-launch
    environment:
      # LD_LIBRARY_PATH: ${SNAP}/usr/local/lib/${SNAP_ARCH_TRIPLET}
      LD_LIBRARY_PATH: ${SNAP}/usr/local/lib/x86_64-linux-gnu
      PATH: ${SNAP}/usr/local/bin
    plugs:
    - login-session-control
    - x11
    - wayland

  tinywl:
    command: tinywl-launch
    environment:
      LD_LIBRARY_PATH: ${SNAP}/usr/local/lib/x86_64-linux-gnu
      PATH: ${SNAP}/usr/local/bin
    plugs:
    - login-session-control
    - x11
    - wayland
